### ISSUE TITLE
Update `new_project` job to add annotations to created dataset folders

### ISSUE THREAD

**Issue by anngvu** [nf-osi/jobs#50]
This helps achieves several things in the short term and long term:
1. Per [internal thread](https://sagebionetworks.slack.com/archives/C01ANC02U5/p1676561742770879?thread_ts=1667943281.698419&cid=C01ANC02U59), this will help DCA pick up on the folders which should be surfaced so they don't have to do custom fixes for us. The bound schema materializes `contentType` = dataset on those folders. The bound schema is inherited automatically by child folders.
2. The assay annotation is put directly on newly created dataset folders. This can help with future functionality: In the DCA or elsewhere, it can be used to more clearly detect which template should be used. If a Synapse dataset is created from the contents, the assay annotation can also be used for the dataset.

**Comment by anngvu** [comment]
Automate:

- assays
- contentType
- progressReportNumber

(Will consider risk of incorrect files being uploaded to folder)

**Comment by jaybee84** [comment]
Yep. this should work for projectLive. It uses `assay` to determine whether a file is labeled annotated
