### ISSUE TITLE
Monitoring for dataStatus changes from "Data Pending" to "Under Embargo"

### ISSUE THREAD

**Issue by anngvu** [nf-osi/jobs#75]
As part of recent updates to semantics of dataStatus, it was agreed that "Data Pending" should change to "Under Embargo" when something is uploaded, and that is a helpful distinction. (See reference discussion [here](https://sagebionetworks.slack.com/archives/C6KQHAGJX/p1699464236849719).) 

Support for this should be through automated monitoring that will update both the Synapse project annotation *and* ~internal tracking~ (actually, internal tracking never had "Data Pending" status because it was added _after_ the set up internal tracking, which defaults to Under Embargo for new projects anyway). Possibly, this can be combined with updated monitoring outlined in #70.

**Comment by allaway** [comment]
You are way ahead of me! I messed around with chatgpt yesterday to write something, no idea if it works: 

https://gist.github.com/allaway/279d2171b1a53c8f3aa0fb65772b86df

note that this only does project annotation, not internal tracking

I'm also curious about a broader question - what else in study annotations can we automate with this sort of logic? e.g. after study end date, automatically transition studyStatus to Completed.
